# Generated by Django 4.2.2 on 2023-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
